### ISSUE TITLE
Error: ChatGPTAPI error 400

### ISSUE THREAD

**Issue by eypu** [ikechan8370/chatgpt-plugin#141]
## 问题描述

[YzBot][03:46:48.006][ERRO] Error: ChatGPTAPI error 400
    at ChatGPTPuppeteer.sendMessage (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:519:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.chatgptBrowserBased (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:436:12)
    at async chatgpt.sendMessage (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:332:14)
    at async chatgpt (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:255:25)
    at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52) {
  statusCode: 400,
  statusText: ''
}

浏览器模式出现的错误，plus 和 普通账号都有错误

**Comment by ikechan8370** [comment]
详细的环境和复现步骤？

**Comment by ikechan8370** [comment]
应该已经修复了
