### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'render')

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#142]
日志内容：
[YzBot][11:32:53.689][ERRO] TypeError: Cannot read properties of undefined (reading 'render')
    at help (file:///C:/Users/Administrator/Desktop/yunzai-bot-lite-master/plugins/chatgpt-plugin/apps/help.js:100:21)
    at PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/yunzai-bot-lite-master/lib/plugins/loader.js:244:55)
    at messageEvent.execute (file:///C:/Users/Administrator/Desktop/yunzai-bot-lite-master/lib/events/message.js:12:18)
    at Yunzai.<anonymous> (file:///C:/Users/Administrator/Desktop/yunzai-bot-lite-master/lib/listener/loader.js:34:81)
    at Yunzai.emit (node:events:512:28)
    at Yunzai.em (C:\Users\Administrator\Desktop\yunzai-bot-lite-master\node_modules\.pnpm\oicq@2.3.1_347nexpewnka6j2mj3d6iic3xi\node_modules\oicq\lib\client.js:509:18)
    at Yunzai.handleSyncMsg (C:\Users\Administrator\Desktop\yunzai-bot-lite-master\node_modules\.pnpm\oicq@2.3.1_347nexpewnka6j2mj3d6iic3xi\node_modules\oicq\lib\internal\pbgetmsg.js:131:18)
    at Yunzai.pbGetMsg (C:\Users\Administrator\Desktop\yunzai-bot-lite-master\node_modules\.pnpm\oicq@2.3.1_347nexpewnka6j2mj3d6iic3xi\node_modules\oicq\lib\internal\pbgetmsg.js:57:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Yunzai.eventsListener (C:\Users\Administrator\Desktop\yunzai-bot-lite-master\node_modules\.pnpm\oicq@2.3.1_347nexpewnka6j2mj3d6iic3xi\node_modules\oicq\lib\internal\listeners.js:76:9)

发送 ‘#chatgpt帮助’命令查看帮助会提示这个怎么处理

**Comment by ikechan8370** [comment]
你的Yunzai是啥版本？e.runtime是undefined真没遇到过，除非是特别老的Yunzai可能会这样

**Comment by KasumiYuku** [comment]
> 你的Yunzai是啥版本？e.runtime是undefined真没遇到过，除非是特别老的Yunzai可能会这样

已解决，切换到了高版本的Yunzai
