### ISSUE TITLE
TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#145]
报错原因：[YzBot][14:26:46.284][ERRO] TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded
日志：    at new WaitTask (C:\Users\Administrator\Desktop\Yunzai_Bot\Yunzai-Bot-main\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:34)
    at DOMWorld.waitForSelectorInPage (C:\Users\Administrator\Desktop\Yunzai_Bot\Yunzai-Bot-main\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:432:26)
    at internalHandler.waitFor (C:\Users\Administrator\Desktop\Yunzai_Bot\Yunzai-Bot-main\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Users\Administrator\Desktop\Yunzai_Bot\Yunzai-Bot-main\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:323:29)
    at Frame.waitForSelector (C:\Users\Administrator\Desktop\Yunzai_Bot\Yunzai-Bot-main\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:942:51)
    at Page.waitForSelector (C:\Users\Administrator\Desktop\Yunzai_Bot\Yunzai-Bot-main\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2370:33)
    at file:///C:/Users/Administrator/Desktop/Yunzai_Bot/Yunzai-Bot-main/plugins/chatgpt-plugin/utils/openai-auth.js:59:14
    at file:///C:/Users/Administrator/Desktop/Yunzai_Bot/Yunzai-Bot-main/plugins/chatgpt-plugin/utils/openai-auth.js:231:5
    at new Promise (<anonymous>)
    at waitForConditionOrAtCapacity (file:///C:/Users/Administrator/Desktop/Yunzai_Bot/Yunzai-Bot-main/plugins/chatgpt-plugin/utils/openai-auth.js:209:10)

大佬，切换到浏览器后往机器人发了条消息，自动打开了chrome，但没过多久就自己关掉了尽管登录界面已经出现，这是什么原因

**Comment by ikechan8370** [comment]
能看到浏览器界面显示的内容吗？关掉前在哪个页面？

**Comment by KasumiYuku** [comment]
> 能看到浏览器界面显示的内容吗？关掉前在哪个页面？

出现的是停留一下我们正在检查你的浏览器那个页面，过了几s后这个页面就关掉了，然后出现上面那个‘TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded’错误

**Comment by KasumiYuku** [comment]
> 能看到浏览器界面显示的内容吗？关掉前在哪个页面？

![1676272591331](https://user-images.githubusercontent.com/107661829/218394489-6a9ac570-994c-4cbe-a6bb-cfb5d9df27ac.jpg)

chatgpt re-authenticating afkeru5061@gmail.com
[YzBot][15:16:11.412][INFO] init chatgpt browser
[YzBot][15:16:11.413][MARK] chatgpt puppeteer 启动中...
[YzBot][15:16:18.040][MARK] chatgpt puppeteer 启动成功
[YzBot][15:16:25.568][INFO] 需要登录，准备进行自动化登录
[YzBot][15:16:26.536][MARK] chatgpt checkForChatGPTAtCapacity
[YzBot][15:16:26.891][MARK] chatgpt checkForChatGPTAtCapacity again
[YzBot][15:16:36.150][INFO] Chromium实例关闭或崩溃！
chatgpt error re-authenticating afkeru5061@gmail.com TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded
[YzBot][15:16:38.174][ERRO] TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded

**Comment by hanyangwendao** [comment]
![image](https://user-images.githubusercontent.com/31086506/218418819-0263e8ec-de93-404f-ab35-7c2f873b7d88.png)
我也遇到了同样的类似的问题，使用的是无头模式，配置了2captchaToken仍然无法生效
![image](https://user-images.githubusercontent.com/31086506/218419222-26e66ad5-2091-48a8-b4ee-3d98862eb03d.png)

**Comment by KasumiYuku** [comment]
@ikechan8370 大佬这个是什么原因啊

**Comment by ikechan8370** [comment]
> > 能看到浏览器界面显示的内容吗？关掉前在哪个页面？
> 
> ![1676272591331](https://user-images.githubusercontent.com/107661829/218394489-6a9ac570-994c-4cbe-a6bb-cfb5d9df27ac.jpg)
> 
> chatgpt re-authenticating [afkeru5061@gmail.com](mailto:afkeru5061@gmail.com) [YzBot][15:16:11.412][INFO] init chatgpt browser [YzBot][15:16:11.413][MARK] chatgpt puppeteer 启动中... [YzBot][15:16:18.040][MARK] chatgpt puppeteer 启动成功 [YzBot][15:16:25.568][INFO] 需要登录，准备进行自动化登录 [YzBot][15:16:26.536][MARK] chatgpt checkForChatGPTAtCapacity [YzBot][15:16:26.891][MARK] chatgpt checkForChatGPTAtCapacity again [YzBot][15:16:36.150][INFO] Chromium实例关闭或崩溃！ chatgpt error re-authenticating [afkeru5061@gmail.com](mailto:afkeru5061@gmail.com) TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded [YzBot][15:16:38.174][ERRO] TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 2000ms exceeded

这是超时了。你网太慢了可能 我设了5*2=10秒的等待时间

**Comment by ikechan8370** [comment]
> @ikechan8370 大佬这个是什么原因啊

无头模式用不了，参照readme安装个虚拟桌面吧
