### ISSUE TITLE
修改config.js后出现报错

### ISSUE THREAD

**Issue by Haku530** [ikechan8370/chatgpt-plugin#176]
配置文件大多是默认，使用的是API3
以下是报错内容
[YzBot][18:43:54.081][INFO] 加载插件中..
[YzBot][18:43:54.330][ERRO] 载入插件错误：chat
[YzBot][18:43:54.331][ERRO] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at file:///C:/zbt/Yunzai-Bot/plugins/chatgpt-plugin/utils/config.js:33:3 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
[YzBot][18:43:54.336][ERRO] 载入插件错误：help
[YzBot][18:43:54.337][ERRO] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at file:///C:/zbt/Yunzai-Bot/plugins/chatgpt-plugin/utils/config.js:33:3 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
[YzBot][18:43:54.339][ERRO] 载入插件错误：management
[YzBot][18:43:54.340][ERRO] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at file:///C:/zbt/Yunzai-Bot/plugins/chatgpt-plugin/utils/config.js:33:3 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'

**Comment by CuteLeaf** [comment]
拉取最新版本

**Comment by Haku530** [comment]
我通过不用config里的config.js，而是修改utils里的config.js成功运行了

**Comment by loveNin** [comment]
我刚刚试了，config下面不要config.js，改utils下面config.js可以成功运行（注意config下面不要config.js）

**Comment by HalcyonAlcedo** [comment]
这个问题应该只出现在Windows上，最新版本已经修复了这个bug，尽量不要将配置写在utils中的config里，会影响自动更新

**Comment by loveNin** [comment]
没有哦，我是centos7.6

**Comment by HalcyonAlcedo** [comment]
> 没有哦，我是centos7.6

也是同样的报错吗，能否贴出具体报错内容，

**Comment by loveNin** [comment]
> > 没有哦，我是centos7.6
> 
> 也是同样的报错吗，能否贴出具体报错内容，



> > 没有哦，我是centos7.6
> 
> 也是同样的报错吗，能否贴出具体报错内容，

和上面描述的差不多，也是 载入插件错误：caht   载入插件错误：help  载入插件错误：management，因为日志已经被删除了，不确定细节是否一致

**Comment by HalcyonAlcedo** [comment]
上面的问题是应为windows目录无法被正确导入导致的，linux应该不存在这种问题，最好还是有日志，不然无法确认具体问题
