### ISSUE TITLE
 Error: ChatGPT invalid apiKey

### ISSUE THREAD

**Issue by nilfunc** [ikechan8370/chatgpt-plugin#185]
Error: ChatGPT invalid apiKey
    at new ChatGPTAPI (file:///D:/AAAA%E6%B8%B8%E6%88%8F/Yunzai-Bot/node_modules/.pnpm/registry.npmmirror.com+chatgpt@4.7.2/node_modules/chatgpt/build/index.js:136:13)
    at chatgpt.sendMessage (file:///D:/AAAA%E6%B8%B8%E6%88%8F/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:645:27)
    at chatgpt (file:///D:/AAAA%E6%B8%B8%E6%88%8F/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:372:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///D:/AAAA%E6%B8%B8%E6%88%8F/Yunzai-Bot/lib/plugins/loader.js:251:52)

**Comment by nilfunc** [comment]
已解决，换了key
