### ISSUE TITLE
Sydney模式下的toLowerCase错误

### ISSUE THREAD

**Issue by heisenyu** [ikechan8370/chatgpt-plugin#238]
[MiaoYz][17:41:23.557][ERRO] TypeError: Cannot read property 'toLowerCase' of undefined
    at file:///root/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:606:65
    at Array.find (<anonymous>)
    at chatgpt (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:606:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:255:54)

**Comment by heisenyu** [comment]
已解决，因为有表情的原因无法正常toLowerCase()，注释掉就行了：
      // 检索是否有屏蔽词
//      const blockWord = Config.blockWords.find(word => response.toLowerCase().includes(word.toLowerCase()))
//      const blockWord = Config.blockWords.find(word => response.includes(word))
//      if (blockWord) {
//        await this.reply('返回内容存在敏感词，我不想回答你', true)
//        return false
//      }


不过我不会javaScript的语法，知道怎么改的小伙伴可以回复一下

**Comment by ikechan8370** [comment]
已修复
