### ISSUE TITLE
载入插件错误报错 Error: ENOENT: no such file or directory, scandir './plugins/chatgpt-plugin/apps'

### ISSUE THREAD

**Issue by junity233** [ikechan8370/chatgpt-plugin#26]
日志如下:
```
[YzBot][17:02:57.593][INFO] 加载插件中..
[YzBot][17:02:57.608][ERRO] 载入插件错误：chatgpt
[YzBot][17:02:57.608][ERRO] Error: ENOENT: no such file or directory, scandir './plugins/chatgpt-plugin/apps'
    at Object.readdirSync (node:fs:1451:3)
    at file:///root/chat-gpt-qq/Yunzai-Bot/plugins/chatgpt/index.js:3:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async PluginsLoader.load (file:///root/chat-gpt-qq/Yunzai-Bot/lib/plugins/loader.js:50:19)
    at async onlineEvent.execute (file:///root/chat-gpt-qq/Yunzai-Bot/lib/events/online.js:23:5)
```

**Comment by cXp1r** [comment]
同问
