### ISSUE TITLE
给bing添加扩展资料后，一直回复“InvalidRequest: Request can't have PreviousMessages for an existing conversation.”

### ISSUE THREAD

**Issue by ifeif** [ikechan8370/chatgpt-plugin#333]
## 问题描述

给bing添加扩展资料以后，第一次回复正常，之后bing一直回复“InvalidRequest: Request can't have PreviousMessages for an existing conversation.”

## 预期行为

给bing添加扩展资料，希望bing根据扩展资料回答
## 实际行为

给bing添加扩展资料以后，第一次回复正常，之后bing一直回复“InvalidRequest: Request can't have PreviousMessages for an existing conversation.”

## 复制过程

1.给bing添加扩展资料
2.跟bing聊天
3.bing一直回复“InvalidRequest: Request can't have PreviousMessages for an existing conversation.”
## 环境

插件最新版

## 可能的解决方案

删除bing的扩展资料后，bing 的回复正常，并且在对话结束前bing已学习到扩展资料。
我认为可能的解决方案：开启新对话时给bing发送扩展资料，之后的对话不再发送扩展资料。

## 附加信息

[13:48:01.416][ERRO] Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.
    at WebSocket.<anonymous> (file:///home/chen/Yunzai-Bot/node_modules/.pnpm/@waylaidwanderer+chatgpt-api@1.33.2/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:438:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
[13:48:02.310][ERRO] Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.
    at WebSocket.<anonymous> (file:///home/chen/Yunzai-Bot/node_modules/.pnpm/@waylaidwanderer+chatgpt-api@1.33.2/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:438:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
[13:48:03.270][ERRO] Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.
    at WebSocket.<anonymous> (file:///home/chen/Yunzai-Bot/node_modules/.pnpm/@waylaidwanderer+chatgpt-api@1.33.2/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:438:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/home/chen/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)

**Comment by ikechan8370** [comment]
若要添加扩展请勿使用精准/平衡/创意模式

**Comment by ifeif** [comment]
> 若要添加扩展请勿使用精准/平衡/创意模式若要添加扩展请勿使用精准/平衡/创意模式若要添加扩展请勿使用精准/平衡/创意模式

sydney模式和Custom模式存在封号的风险吗？

**Comment by ifeif** [comment]
> 若要添加扩展请勿使用精准/平衡/创意模式

使用sydney模式和Custom模式之后，bing可以学习到拓展资料，但是效果没有精准/平衡/创意模式好。

**Comment by Err0rCM** [comment]
如还有问题请重开issue
