### ISSUE TITLE
channel_not_found 问题

### ISSUE THREAD

**Issue by yhny1001** [ikechan8370/chatgpt-plugin#427]
关于Claude 在使用slack指定频道时指定一个已有频道显示 channel_not_found
但在slack里已有聊天的和输入的记录 估计问题出在输出端上

**Comment by heisenyu** [comment]
我也遇到了这个问题，指定频道的话 会报错channel_not_found，但在slack中是正常显示的。

[ERRO] Error: An API error occurred: channel_not_found
    at platformErrorFromResult (/root/TRSS_Yunzai/Miao-Yunzai/node_modules/.pnpm/@slack+web-api@6.8.1/node_modules/@slack/web-api/dist/errors.js:56:33)
    at WebClient.apiCall (/root/TRSS_Yunzai/Miao-Yunzai/node_modules/.pnpm/@slack+web-api@6.8.1/node_modules/@slack/web-api/dist/WebClient.js:181:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SlackClaudeClient.sendMessage (file:///root/TRSS_Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/utils/slack/slackClient.js:83:23)
    at async chatgpt.sendMessage (file:///root/TRSS_Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1801:20)
    at async chatgpt.abstractChat (file:///root/TRSS_Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:967:25)
    at async chatgpt (file:///root/TRSS_Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:780:5)
    at async PluginsLoader.deal (file:///root/TRSS_Yunzai/Miao-Yunzai/lib/plugins/loader.js:267:54) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'channel_not_found',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
