### ISSUE TITLE
更新到最新版本后插件启动报错

### ISSUE THREAD

**Issue by BIMOQS** [ikechan8370/chatgpt-plugin#489]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

更新后提示需要安装依赖，执行 pnpm add @fastify/websocket -w 后，插件启动报错：

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

[08:55:01.364][ERRO] 载入插件错误：[31mchatgpt-plugin[39m
[08:55:01.364][ERRO] TypeError: Cannot destructure property 'Serializer' of 'dependencies' as it is undefined.
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-serializer.js:7:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-handler.js:20:24)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[08:55:01.366][ERRO] TypeError: Cannot destructure property 'Serializer' of 'dependencies' as it is undefined.
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-serializer.js:7:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-handler.js:20:24)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)

## 复制过程

#全部更新
更新完毕，手动重启
node app

[07:55:20.886][MARK] --------插件载入错误--------
[07:55:20.887][MARK] chatgpt-plugin 缺少依赖：@fastify/websocket
[07:55:20.887][MARK] 请执行安装依赖命令：pnpm add @fastify/websocket -w
[07:55:20.887][MARK] ---------------------

关闭
安装依赖
node app

[08:55:01.364][ERRO] 载入插件错误：[31mchatgpt-plugin[39m
[08:55:01.364][ERRO] TypeError: Cannot destructure property 'Serializer' of 'dependencies' as it is undefined.
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-serializer.js:7:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-handler.js:20:24)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[08:55:01.366][ERRO] TypeError: Cannot destructure property 'Serializer' of 'dependencies' as it is undefined.
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-serializer.js:7:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Yunzai-Bot\node_modules\.pnpm\fastify@4.16.0\node_modules\fastify\lib\error-handler.js:20:24)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)

## 环境

W10系统

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
我也遇到了 我的解决方案是在chatgpt-plugin目录下执行npm i安装依赖，而不是pnpm

**Comment by Yoraka** [comment]
我直接把fastify换到4.18.0版本就没报错了

**Comment by ikechan8370** [comment]
应该本质不是fastify版本的问题 可能是pnpm依赖管理的bug 重新装基本就好了
