### ISSUE TITLE
没法调用我的puppeteer chromium

### ISSUE THREAD

**Issue by M0refish** [ikechan8370/chatgpt-plugin#49]
使用默认chorme位置
![image](https://user-images.githubusercontent.com/120435537/207503242-04052d3f-4f0d-4369-a84c-30e1fefe7d5d.png)

使用自己chorme位置
![image](https://user-images.githubusercontent.com/120435537/207503199-0f530d10-94c7-4748-b7f3-47bcada597e5.png)

但云崽等其他插件调用没问题。

**Comment by YujioNako** [comment]
我也一样，miao-plugin等插件都能正常调用，但在chatgtp-plugin下会显示

    [13:01:59.846][MARK] puppeteer Chromium 启动中...
    [13:02:00.833][ERRO] Error: Failed to launch the browser process!
    [1904710:1904710:1214/130200.809868:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
    [1904710:1904710:1214/130200.810763:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
    [1214/130200.828778:ERROR:nacl_helper_linux.cc(315)] NaCl helper process running without a sandbox!
    Most likely you need to configure your SUID sandbox correctly


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    [13:02:00.834][ERRO] puppeteer Chromium 启动失败
    [13:02:00.846][ERRO] [chatgpt][chatgpt]
    [13:02:00.846][ERRO] Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/www/wwwroot/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/www/wwwroot/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by SakuragiKuroko** [comment]
俺也一样

**Comment by yuweiliang111** [comment]
看来都没解决

**Comment by chen8665272** [comment]
#https://github.com/puppeteer/puppeteer/issues/8148

**Comment by chen8665272** [comment]
可能是运行在没有图形界面的Linux环境，Chromium调用不出GUI页面

**Comment by shirosoralumie648** [comment]
装了个google- chrome-stable
然后把browser.js第52行改成这样
this.browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] })(this.config).catch((err) => {
之后是这样的
0|Yunzai-Bot  | Error: Failed to launch the browser process!
0|Yunzai-Bot  | [39916:39916:1215/214222.231803:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
0|Yunzai-Bot  | [39916:39916:1215/214222.232092:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
0|Yunzai-Bot  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|Yunzai-Bot  |     at onClose (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
0|Yunzai-Bot  |     at ChildProcess.<anonymous> (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:232:79)
0|Yunzai-Bot  |     at ChildProcess.emit (node:events:525:35)
0|Yunzai-Bot  |     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
0|Yunzai-Bot  | [YzBot][21:42:22.247][ERRO] [chatgpt][chatgpt]
0|Yunzai-Bot  | [YzBot][21:42:22.248][ERRO] Error: Failed to launch the browser process!
0|Yunzai-Bot  | [39916:39916:1215/214222.231803:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
0|Yunzai-Bot  | [39916:39916:1215/214222.232092:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
0|Yunzai-Bot  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|Yunzai-Bot  |     at onClose (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
0|Yunzai-Bot  |     at ChildProcess.<anonymous> (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:232:79)
0|Yunzai-Bot  |     at ChildProcess.emit (node:events:525:35)
0|Yunzai-Bot  |     at ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by chen8665272** [comment]
可能需要调用图形界面吧

**Comment by chen8665272** [comment]
https://github.com/puppeteer/puppeteer/issues/8148

**Comment by yuanmochu** [comment]
你的也是centos系统吗？

**Comment by zeroasj** [comment]
遇到了同样的问题

**Comment by myself147** [comment]
centos8
node 18.4
也有同样的问题
