### ISSUE TITLE
回复报错Unexpected server response: 200

### ISSUE THREAD

**Issue by Luminometor** [ikechan8370/chatgpt-plugin#498]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

在大约两个月之前bing模式的回复总是报错Unexpected server response: 403，重装bot和插件都无法解决，就没有再继续处理下去了，在昨天也就是6月29号bot的qq号显示被限制非常用设备，目前无法解封，因此换了一个qq号，之后尝试chatgpt插件bing模式，bot回复Unexpected server response: 200

## 预期行为
请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

[YzBot][11:24:32.549][INFO] recv from: [Private: 2859751343(group)] 你好
[YzBot][11:24:32.564][INFO] chatgpt prompt: 你好
[YzBot][11:24:32.565][INFO] {
  previousConversation: {
    sender: {
      user_id: 2859751343,
      nickname: '之^4',
      group_id: 315108181,
      card: '之^4'
    },
    ctime: '2023-06-30T03:24:32.564Z',
    utime: '2023-06-30T03:24:32.564Z',
    num: 0,
    conversation: {}
  }
}
[YzBot][11:24:32.565][MARK] {
  conversation: {
    conversationId: undefined,
    parentMessageId: undefined,
    clientId: undefined,
    invocationId: undefined,
    conversationSignature: undefined,
    bingToken: undefined
  }
}
[YzBot][11:24:32.565][MARK] using bing mode
[YzBot][11:24:32.574][MARK] 使用host：https://666102.201666.xyz
{
  conversationId: '51D|BingProd|EF72DB628AD1A950ED4EFB5C256CEFF1291E3DB62976C8BAA48331368BF88A47',
  clientId: '985154250814461',
  conversationSignature: '/DZypFJQpg5rfYMD9WXzekRRb3cJQJaoOqQRl9YUK5E=',
  result: { value: 'Success', message: null }
}
[YzBot][11:24:34.454][MARK] use sydney websocket host: wss://sydney.bing.com
Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\28597\Downloads\bot\Yunzai-Bot\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
disconnected
[YzBot][11:24:34.698][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\28597\Downloads\bot\Yunzai-Bot\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[YzBot][11:24:34.702][MARK] 使用host：https://666102.201666.xyz
{
  conversationId: '51D|BingProd|E446B4B4D04A5A3AB81710469A91C1A51E203C622CB5B161F22290CD4ADDED7C',
  clientId: '985154250814461',
  conversationSignature: 'jDYx2jlELAD14QGxbAVHtE972OBlBq8w7z7S7EDbvLM=',
  result: { value: 'Success', message: null }
}
[YzBot][11:24:35.393][MARK] use sydney websocket host: wss://sydney.bing.com
Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\28597\Downloads\bot\Yunzai-Bot\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
disconnected
[YzBot][11:24:35.559][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\28597\Downloads\bot\Yunzai-Bot\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[YzBot][11:24:35.563][MARK] 使用host：https://666102.201666.xyz
{
  conversationId: '51D|BingProd|0BC6C6B03B65627616966E6BE9E3E011A4283D94F3617DBB262644DBAC44F63E',
  clientId: '985154250814461',
  conversationSignature: 'ixbNwLtptIxe95x5o+v85AMEUPATRtFB1kvQ8dwqj8Q=',
  result: { value: 'Success', message: null }
}
[YzBot][11:24:36.307][MARK] use sydney websocket host: wss://sydney.bing.com
Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\28597\Downloads\bot\Yunzai-Bot\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
disconnected
[YzBot][11:24:36.488][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\28597\Downloads\bot\Yunzai-Bot\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[YzBot][11:24:36.489][INFO] { text: 'Unexpected server response: 200', error: true }
{"level":30,"time":1688095476492,"pid":25456,"hostname":"LAPTOP-KM8CE4FV","reqId":"req-1f","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remo
teAddress":"::ffff:127.0.0.1","remotePort":57788},"msg":"incoming request"}
{"level":30,"time":1688095476496,"pid":25456,"hostname":"LAPTOP-KM8CE4FV","reqId":"req-1f","res":{"statusCode":200},"responseTime":3.7325000017881393,"msg":"reque
st completed"}
[YzBot][11:24:36.876][INFO] succeed to send: [Private(2859751343)] Unexpected server response: 200

**Comment by ikechan8370** [comment]
我看你日志中，对话的websocket走的是wss://sydney.bing.com，这个需要开启代理。如果没有代理则需要开启“对话使用反代”的选项
