### ISSUE TITLE
chatgpt智能模式报错

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#501]
```
[YzBot][16:21:37.164][ERRO] TypeError: qq.trim is not a function
    at Object.func [as exec] (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/tools/JinyanTool.js:53:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.sendMessage (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:2034:36)
    at async chatgpt.abstractChat (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:995:25)
    at async chatgpt (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:781:5)
    at async PluginsLoader.deal (file:///I:/Yunzai-Bot/lib/plugins/loader.js:274:52)
[YzBot][16:21:37.170][ERRO] Error: TypeError: qq.trim is not a function
    at chatgpt.sendMessage (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:2052:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.abstractChat (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:995:25)
    at async chatgpt (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:781:5)
    at async PluginsLoader.deal (file:///I:/Yunzai-Bot/lib/plugins/loader.js:274:52)
```

**Comment by ikechan8370** [comment]
应该是昨天的merge出的问题 等我看看

**Comment by ghost** [comment]
自己把.trim去掉

**Comment by ikechan8370** [comment]
已修复
