### ISSUE TITLE
bing模式下返回200

### ISSUE THREAD

**Issue by jinyuanfan** [ikechan8370/chatgpt-plugin#502]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

安装完gpt后，选择bing模式，返回200

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

[MiaoYz][10:47:14.437][INFO] chatgpt prompt: 你好
[MiaoYz][10:47:14.438][INFO] {
  previousConversation: {
    sender: { user_id: 954697995, nickname: '飘飞的柳叶', card: '飘飞的柳叶' },
    ctime: '2023-07-03T02:47:14.437Z',
    utime: '2023-07-03T02:47:14.437Z',
    num: 0,
    conversation: {}
  }
}
[MiaoYz][10:47:14.438][MARK] {
  conversation: {
    conversationId: undefined,
    parentMessageId: undefined,
    clientId: undefined,
    invocationId: undefined,
    conversationSignature: undefined,
    bingToken: undefined
  }
}
[MiaoYz][10:47:14.438][MARK] using bing mode
{
  conversationId: '51D|BingProd|DCDC8B1157C381E2D6B944F8390D5486F5FF53969E785E80552C2D7FD110725D',
  clientId: '271B8325B0A060BD13969066B15B61D6',
  conversationSignature: '5LJiMNRKZ58UhPxIe56977VJQ6fxMKDMHRtcPy79lZY=',
  result: { value: 'Success', message: null }
}
disconnected
[MiaoYz][10:47:15.514][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (/root/Miao-Yunzai/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
{
  conversationId: '51D|BingProd|FDACF2C3F14939168588A2301CDBCF61D9520E9F72B7C2FD5BC27CE3DB207F0A',
  clientId: '1794F77594CB654420B3E43695CC6498',
  conversationSignature: 'qrj3qlNlm6vNbQFzlI9UQnpYjSslf8Okkij4Yd2FwFk=',
  result: { value: 'Success', message: null }
}
disconnected
[MiaoYz][10:47:16.595][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (/root/Miao-Yunzai/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
{
  conversationId: '51D|BingProd|179966778B4C592F3B21105A4437424364161474492DE1E1DD41E51AAE253BE1',
  clientId: '21A0C1218EF969143271D2628F7D6873',
  conversationSignature: 'ZYwzb3RG2vI5+YMnGg/tQH86pXcGUoDV8AAKxArjP6Q=',
  result: { value: 'Success', message: null }
}
disconnected
[MiaoYz][10:47:17.468][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (/root/Miao-Yunzai/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[MiaoYz][10:47:17.469][INFO] { text: 'Unexpected server response: 200', error: true }
{"level":30,"time":1688352437473,"pid":81,"hostname":"VM-4-5-centos","reqId":"req-6","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":45998},"msg":"incoming request"}
{"level":30,"time":1688352437475,"pid":81,"hostname":"VM-4-5-centos","reqId":"req-6","res":{"statusCode":200},"responseTime":1.9851740000303835,"msg":"request completed"}

**Comment by jinyuanfan** [comment]
通过后台面板选择了SYDNEY模式，并且启用了返代后，可以聊天，不过无法使用均衡模式。均衡模式已设置token

**Comment by ikechan8370** [comment]
服务器在境内的话目前只能使用悉尼和自定义
