### ISSUE TITLE
设置了必应，不能使用

### ISSUE THREAD

**Issue by haking2019** [ikechan8370/chatgpt-plugin#546]
小白求教，设置了自定义必应，反代设置为https://bing.ikechan8370.com
会返回 404 not found 和 403Forbidden

-------------------------
[MiaoYz][19:26:11.285][ERRO] 创建sydney对话失败: status code: 403Forbidden
[MiaoYz][19:26:11.286][ERRO] response body：
[MiaoYz][19:26:11.286][ERRO] Error: 创建sydney对话失败: status code: 403Forbidden
    at SydneyAIClient.createNewConversation (file:///C:/Users/Administrator/Desktop/Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/utils/SydneyAIClient.js:120:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SydneyAIClient.sendMessage (file:///C:/Users/Administrator/Desktop/Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/utils/SydneyAIClient.js:232:45)
    at async chatgpt.sendMessage (file:///C:/Users/Administrator/Desktop/Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1625:24)
    at async chatgpt.abstractChat (file:///C:/Users/Administrator/Desktop/Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1035:25)
    at async chatgpt (file:///C:/Users/Administrator/Desktop/Yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:815:5)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai/Miao-Yunzai/lib/plugins/loader.js:269:54)
[MiaoYz][19:26:11.287][INFO] { text: '创建sydney对话失败: status code: 403Forbidden', error: true }
{"level":30,"time":1691839571293,"pid":3536,"hostname":"iZrwjw3e36usq3Z","reqId":"req-2","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":49399},"msg":"incoming request"}
{"level":30,"time":1691839571295,"pid":3536,"hostname":"iZrwjw3e36usq3Z","reqId":"req-2","res":{"statusCode":200},"responseTime":2.453990999958478,"msg":"request completed"}
[MiaoYz][19:26:11.492][DEBU] sign MessageSvc.PbSendMsg result(203ms): {"code":0,"data":{"token":"6A327770764D5578484C556A","extra":"121B56315F414E445F53515F382E392E37305F343333305F5959425F441A62585F684C363468574A41414F55384E54343475442F66666D51
705742754C5A32417279436F6A42573847774D6144684772435572454944316B5A676230594F6D6648705638317046623959317574474F6E7973466B7952784B345A4531336E72593D","sign":"0C09AAD90279A86C751CB5294860D313F1BD1EE15D2AF9EE77B7CF213D581ADBEC258F6632FE138F23","o3d
id":"j2wpvMUxHLUj"}}
[MiaoYz][19:26:11.492][DEBU] send:MessageSvc.PbSendMsg seq:996
[MiaoYz][19:26:11.670][DEBU] recv:MessageSvc.PbSendMsg seq:996
[MiaoYz][19:26:11.670][INFO] succeed to send: [Private(353132930)] 创建sydney对话失败: status code: 403Forbidden
[MiaoYz][19:26:36.388][DEBU] send:Client.CorrectTime seq:997
[MiaoYz][19:26:36.394][DEBU] send:OidbSvc.0x480_9_IMCore seq:998
[MiaoYz][19:26:36.455][DEBU] recv:Client.CorrectTime seq:997
[MiaoYz][19:26:36.507][DEBU] recv:OidbSvc.0x480_9_IMCore seq:998
[MiaoYz][19:26:36.522][DEBU] send:Heartbeat.Alive seq:999
[MiaoYz][19:26:36.585][DEBU] recv:Heartbeat.Alive seq:999
[MiaoYz][19:27:36.393][DEBU] send:Client.CorrectTime seq:1000
[MiaoYz][19:27:36.394][DEBU] send:OidbSvc.0x480_9_IMCore seq:1001
[MiaoYz][19:27:36.463][DEBU] recv:Client.CorrectTime seq:1000
[MiaoYz][19:27:36.533][DEBU] recv:OidbSvc.0x480_9_IMCore seq:1001
[MiaoYz][19:27:36.533][DEBU] send:Heartbeat.Alive seq:1002
[MiaoYz][19:27:36.594][DEBU] recv:Heartbeat.Alive seq:1002

**Comment by haking2019** [comment]
![Uploading QQ截图20230812192954.png…]()

**Comment by haking2019** [comment]
之前返回错误200，看之前的issue是ip被拉黑。这个是我重新搞了一个云服务器。
这个错误返回也非常慢。
求助，谢谢大佬们。

**Comment by ikechan8370** [comment]
日志没有截到有用信息

**Comment by haking2019** [comment]
你发来的邮件我已收到。

**Comment by haking2019** [comment]
你发来的邮件我已收到。

**Comment by haking2019** [comment]
你发来的邮件我已收到。
