### ISSUE TITLE
挂代理和不挂代理，换了几次token还是万恶的Unexpected server response: 200

### ISSUE THREAD

**Issue by Accelerator23333** [ikechan8370/chatgpt-plugin#554]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息
[MiaoYz][11:38:26.319][INFO] recv from: [Private: 3218801776(friend)] #chatgpt设置必应token
[MiaoYz][11:38:26.321][MARK] [ChatGPT-Plugin 管理][setBingAccessToken][私聊][学习(3218801776)] #chatgpt设置必应token
[MiaoYz][11:38:26.500][INFO] succeed to send: [Private(3218801776)] [回复]请发送Bing Cookie Token.("_U" cookie from bing.com)
[MiaoYz][11:38:33.006][INFO] recv from: [Private: 3218801776(friend)] 打码
[MiaoYz][11:38:33.158][INFO] succeed to send: [Private(3218801776)] [回复]Bing Token设置成功
[MiaoYz][11:38:33.632][MARK] 使用host：https://666102.201666.xyz
[MiaoYz][11:38:34.802][INFO] bing token 有效
[MiaoYz][11:38:58.639][INFO] recv from: [Group: 小号群(397490258), Member:                                  (3218801776)] {at:2802905304} 早
[MiaoYz][11:39:03.863][ERRO] 发送消息错误:我正在思考如何回复你，请稍等
[MiaoYz][11:39:03.864][ERRO] ApiRejection { code: -70, message: '群消息发送失败，可能被风控' }
[MiaoYz][11:39:03.866][INFO] chatgpt prompt: 早
[MiaoYz][11:39:03.866][INFO] {
  previousConversation: {
    sender: {
      user_id: 3218801776,
      nickname: '学习',
      sub_id: 537173576,
      card: '                                 ',
      sex: 'female',
      age: 22,
      area: '加拿大',
      level: 2,
      role: 'owner',
      title: ''
    },
    ctime: '2023-08-28T03:39:03.866Z',
    utime: '2023-08-28T03:39:03.866Z',
    num: 0,
    messages: [ [Object] ],
    conversation: {}
  }
}
[MiaoYz][11:39:03.869][MARK] {
  conversation: {
    messages: [ [Object] ],
    conversationId: undefined,
    parentMessageId: undefined,
    clientId: undefined,
    invocationId: undefined,
    conversationSignature: undefined,
    bingToken: undefined
  }
}
[MiaoYz][11:39:03.869][MARK] using bing mode
{
  conversationId: '51D|BingProd|863DAEE3443B4E622BB4A78D5DF3C918EA01E985094B116CA654B87C0DF57F8F',
  clientId: '844426282992261',
  conversationSignature: 'apR2r9Dtnh0FwFGVKfP2XenrK7g+739kYbWmtqEIZaE=',
  result: { value: 'Success', message: null }
}
disconnected
[MiaoYz][11:39:07.893][ERRO] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
[MiaoYz][11:39:15.802][ERRO] Error: /turing/conversation/create: failed to parse response body.
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

    at BingAIClient.createNewConversation (file:///G:/yunzai/Miao-Yunzai/node_modules/.pnpm/@waylaidwanderer+chatgpt-api@1.37.3/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:124:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BingAIClient.sendMessage (file:///G:/yunzai/Miao-Yunzai/node_modules/.pnpm/@waylaidwanderer+chatgpt-api@1.37.3/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:220:51)
    at async chatgpt.sendMessage (file:///G:/yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1682:24)
    at async chatgpt.abstractChat (file:///G:/yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1076:25)
    at async chatgpt (file:///G:/yunzai/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:846:5)
    at async PluginsLoader.deal (file:///G:/yunzai/Miao-Yunzai/lib/plugins/loader.js:269:54)
{
  conversationId: '51D|BingProd|BEE79EEAF8B7A5D1D79586DD57D54D9F3A0E125C295B4BCCA2C2E82DE49939BE',
  clientId: '844426282992261',
  conversationSignature: 'ttwlVFrS/nCrXSAOREE5a6nU9wj+dw+7nq/JmVUS+DU=',
  result: { value: 'Success', message: null }
}
disconnected
[MiaoYz][11:39:16.994][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (G:\yunzai\Miao-Yunzai\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[MiaoYz][11:39:16.995][INFO] { text: 'Unexpected server response: 200', error: true }
{"level":30,"time":1693193956997,"pid":17204,"hostname":"DESKTOP-G92MMRQ","reqId":"req-16","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":31070},"msg":"incoming request"}
{"level":30,"time":1693193956999,"pid":17204,"hostname":"DESKTOP-G92MMRQ","reqId":"req-16","res":{"statusCode":200},"responseTime":1.576300024986267,"msg":"request completed"}
[MiaoYz][11:39:22.266][ERRO] 发送消息错误:["Unexpected server response: 200"]
[MiaoYz][11:39:22.266][ERRO] ApiRejection { code: -70, message: '群消息发送失败，可能被风控' }
如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by Accelerator23333** [comment]
用的是miao版的云仔不知道是不是这个问题
风控那个之后再调

**Comment by ikechan8370** [comment]
使用代理请切换至悉尼/自定义模式
