### ISSUE TITLE
azure语音报错！

### ISSUE THREAD

**Issue by wzq10314** [ikechan8370/chatgpt-plugin#577]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by wzq10314** [comment]
错误代码如下
[MiaoYz][15:06:04.703][ERRO] ReferenceError: e is not defined
    at uploadRecord (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/utils/uploadRecord.js:142:17)
    at async generateAzureAudio (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/utils/common.js:944:12)
    at async generateAudio (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/utils/common.js:856:14)
    at async chatgpt.abstractChat (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1258:26)
    at async chatgpt (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:821:5)
    at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:269:54)
[MiaoYz][15:06:05.900][INFO] succeed to send: [Group(163722659)] 合成语音发生错误~

**Comment by sizxiwu** [comment]
怎么解决

**Comment by wzq10314** [comment]
> 怎么解决

还没有解决

**Comment by ikechan8370** [comment]
这个周末统一解决

**Comment by wzq10314** [comment]
> 这个周末统一解决

辛苦了
