### ISSUE TITLE
合成语音成功后，无法获取语音长度发不出来

### ISSUE THREAD

**Issue by misaka20002** [ikechan8370/chatgpt-plugin#588]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

合成语音成功后，无法获取语音长度发不出来。
报错：
ReferenceError: e is not defined

## 预期行为

获取语音后发送出来

## 实际行为

无法获取语音长度发不出来

## 环境

miao-yunzai
Android

以及

trss-yunzai
Windows

## 附加信息

倒序：
[16:09:46.117][ERRO] ApiRejection { code: -60, message: '音频转码到amr失败，请确认你的ffmpeg可以处理此转换' }
[16:09:46.116][ERRO] 发送消息错误:{"type":"record","file":"https://misaka20001-paimon-is-not-a-food.hf.space/file=/tmp/tmpb3ymqx01/tmpmc4a2voq.wav"}
    at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:282:54)
    at async chatgpt (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:827:5)
    at async chatgpt.abstractChat (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1264:26)
    at async generateAudio (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/utils/common.js:882:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at uploadRecord (file:///root/Miao-Yunzai/plugins/chatgpt-plugin/utils/uploadRecord.js:142:17)
[16:09:36.404][ERRO] ReferenceError: e is not defined
[16:09:31.692][MARK] 使用云转码silk进行高清语音生成:"
[16:08:47.850][MARK] sydney websocket constructed successful

**Comment by ikechan8370** [comment]
已知bug 近期修复
