### ISSUE TITLE
为啥使用Bard报错

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#591]
浏览器上可以打开bard.google.com，但Bot却提示这个：
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/2e0f365d-cffc-41d4-8013-ea40c450827a)

**Comment by KeluIsAfkeru** [comment]
qaq

**Comment by ikechan8370** [comment]
这是你连不上bard.google.com吧

**Comment by KasumiYuku** [comment]
> 这是你连不上bard.google.com吧

@ikechan8370 现在连接问题搞定了，但是对话时报错：
TypeError: Cannot read properties of null (reading '4')
    at #query (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/utils/bard.js:243:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Chat.ask (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/utils/bard.js:356:30)
    at async chatgpt.sendMessage (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:2028:24)
    at async chatgpt.abstractChat (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1069:25)
    at async chatgpt (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:835:5)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/lib/plugins/loader.js:269:54)

![M8MW9U}LE93WQQHF5 G8T L](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/4e6ff8f5-8b85-4890-960a-d6a4e7115408)

**Comment by ikechan8370** [comment]
@HalcyonAlcedo

**Comment by KasumiYuku** [comment]
有解决方法了嘛大佬）

**Comment by czjdr** [comment]
@KeluIsAfkeru 你好，请问__Secure-1PSIDTS是怎么找到的？我只找到了__Secure-1PSID,__Secure-1PSIDCC还有__Secure-1PAPISID
