### ISSUE TITLE
[BUG]出验证码不会返回提示，限流以后会不停的重试直到遇到其他错误而停止

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#624]
```
0|Miao-Yunzai  | [MiaoYz][22:27:28.839][WARN] 该账户的SERP请求已被限流
0|Miao-Yunzai  | [MiaoYz][22:27:28.840][WARN] {"value":"Throttled","message":"Request is throttled.","error":"Request is throttled.","serviceVersion":"20231213.58"}
0|Miao-Yunzai  | [MiaoYz][22:27:28.842][ERRO] TypeError: Cannot create property 'conversation' on string '该账户的SERP请求已被限流'
0|Miao-Yunzai  |     at SydneyAIClient.sendMessage (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/utils/SydneyAIClient.js:848:24)
0|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Miao-Yunzai  |     at async chatgpt.sendMessage (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1739:24)
0|Miao-Yunzai  |     at async chatgpt.abstractChat (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1124:25)
0|Miao-Yunzai  |     at async chatgpt (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:886:5)
0|Miao-Yunzai  |     at async PluginsLoader.deal (file:///I:/Miao-Yunzai/lib/plugins/loader.js:291:54)
```

**Comment by tsfeng6** [comment]
同样的问题
