### ISSUE TITLE
【功能请求】希望能适配LLOnebot的群聊记录接口

### ISSUE THREAD

**Issue by ElaineOwO** [ikechan8370/chatgpt-plugin#668]
RT [LLonebot](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.17.0)刚刚更新了获取群聊记录的接口api`/get_group_msg_history`  但插件仍然获取不到记录，提示如下
` 获取群聊聊天记录失败，本次对话不携带聊天记录 TypeError: e.group.getChatHistory is not a function
    at getChatHistoryGroup (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/utils/chat.js:8:35)
    at chatgpt.sendMessage (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/model/core.js:202:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.abstractChat (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:794:25)
    at async chatgpt (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:559:5)
    at async PluginsLoader.deal (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/lib/plugins/loader.js:254:41)`
希望大佬能麻烦做一下适配啦
球球叻 我什么都会做的QAQ

**Comment by ikechan8370** [comment]
这个是要适配器去适配的 插件这边应该做不了什么 你是什么适配器呢？

**Comment by ElaineOwO** [comment]
> 这个是要适配器去适配的 插件这边应该做不了什么 你是什么适配器呢？
嗯，，我是小白不太懂什么叫适配器 不过我用的是NTQQ  加[LiteLoaderQQNT](https://liteloaderqqnt.github.io/)+[LLOnebot](https://github.com/LLOneBot/LLOneBot?tab=readme-ov-file)

**Comment by ElaineOwO** [comment]
> 这个是要适配器去适配的 插件这边应该做不了什么 你是什么适配器呢？

嗯，，我是小白不太懂什么叫适配器 不过我用的是NTQQ 加[LiteLoaderQQNT](https://liteloaderqqnt.github.io/)+[LLOnebot](https://github.com/LLOneBot/LLOneBot?tab=readme-ov-file)

**Comment by ikechan8370** [comment]
> > 这个是要适配器去适配的 插件这边应该做不了什么 你是什么适配器呢？
> 
> 嗯，，我是小白不太懂什么叫适配器 不过我用的是NTQQ 加[LiteLoaderQQNT](https://liteloaderqqnt.github.io/)+[LLOnebot](https://github.com/LLOneBot/LLOneBot?tab=readme-ov-file)

是说你机器人这边 用什么接的？

**Comment by ElaineOwO** [comment]
> > > 这个是要适配器去适配的 插件这边应该做不了什么 你是什么适配器呢？
> > 
> > 
> > 嗯，，我是小白不太懂什么叫适配器 不过我用的是NTQQ 加[LiteLoaderQQNT](https://liteloaderqqnt.github.io/)+[LLOnebot](https://github.com/LLOneBot/LLOneBot?tab=readme-ov-file)
> 
> 是说你机器人这边 用什么接的？

用的是TRSS崽

**Comment by ElaineOwO** [comment]
> > > 这个是要适配器去适配的 插件这边应该做不了什么 你是什么适配器呢？
> > 
> > 
> > 嗯，，我是小白不太懂什么叫适配器 不过我用的是NTQQ 加[LiteLoaderQQNT](https://liteloaderqqnt.github.io/)+[LLOnebot](https://github.com/LLOneBot/LLOneBot?tab=readme-ov-file)
> 
> 是说你机器人这边 用什么接的？

刚刚又跑去问了时雨，时雨说之后会适配。应该慢慢等就好了吧(大概)
