### ISSUE TITLE
Cannot find module './jieba.win32-x64-msvc.node'

### ISSUE THREAD

**Issue by Jin1c-3** [ikechan8370/chatgpt-plugin#719]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

在加载 `entertainment.js` 时出现了依赖错误，每次都会出现：

```
[09:58:30.780][ERRO][34m[  TRSSYz  ][39m 载入插件错误：[31mentertainment[39m
[09:58:30.782][ERRO][34m[  TRSSYz  ][39m Error: Failed to load native binding
    at Object.<anonymous> (C:\Users\Administrator\Yunzai\node_modules\.pnpm\@node-rs+jieba@1.10.4\node_modules\@node-rs\jieba\index.js:359:11)
    ...(省略)
    at async file:///C:/Users/Administrator/yunzai/plugins/chatgpt-plugin/index.js:24:7 {
  [cause]: [
    Error: Cannot find module './jieba.win32-x64-msvc.node'
    Require stack:
    - C:\Users\Administrator\Yunzai\node_modules\.pnpm\@node-rs+jieba@1.10.4\node_modules\@node-rs\jieba\index.js
         ...(省略)
        at async file:///C:/Users/Administrator/yunzai/plugins/chatgpt-plugin/index.js:24:7 {
      code: 'MODULE_NOT_FOUND',
      requireStack: [Array]
    },
    Error: The specified module could not be found.
    \\?\C:\Users\Administrator\Yunzai\node_modules\.pnpm\@node-rs+jieba-win32-x64-msvc@1.10.4\node_modules\@node-rs\jieba-win32-x64-msvc\jieba.win32-x64-msvc.node
         ...(省略)
        at async file:///C:/Users/Administrator/yunzai/plugins/chatgpt-plugin/index.js:24:7 {
      code: 'ERR_DLOPEN_FAILED'
    }
  ]
}
```

## 预期行为

我使用 `pnpm add jieba -w` 和 `pnpm add @node-rs/jieba -w` 安装了相应模块，并且 `node-modules` 文件夹里面有 `/jieba.win32-x64-msvc.node` 这个文件，理应正常加载。当然这也可能是 `jieba` 的问题吧，但我上网搜索后没有找到相应的解答，只好提个 `issue` 了。。。

## 实际行为

报错， `entertainment.js· 无法正确加载

## 复制过程

启动即报错

## 环境

windows server 2022+trss-yunzai+NapCat-LiteLoader插件

## 可能的解决方案

上文已经陈述

## 附加信息

日志已经提供

**Comment by Jin1c-3** [comment]
我刚刚看到了之前相同的 `issue` ，我卸载重装了 `@node-rs/jieba` 和 `@node-rs/jieba-win32-x64-msvc` ，但问题依旧

**Comment by Jin1c-3** [comment]
已经解决，因为Windows server缺少dll导致，可以在此处下载：https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
类似的issue：https://github.com/QwikDev/qwik/issues/3704
