### ISSUE TITLE
现在好像不支持新的openai

### ISSUE THREAD

**Issue by SaltyFishAB** [ikechan8370/chatgpt-plugin#726]
[MiaoYz][18:03:49.153][ERRO] 载入插件错误：chat
[MiaoYz][18:03:49.153][ERRO] file:///home/user/Miao-Yunzai/plugins/chatgpt-plugin/utils/dalle.js:1
import { Configuration, OpenAIApi } from 'openai'
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'openai' does not provide an export named 'Configuration'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async Promise.allSettled (index 1)
    at async file:///home/user/Miao-Yunzai/plugins/chatgpt-plugin/index.js:24:7
[MiaoYz][18:03:49.153][ERRO] 载入插件错误：draw
[MiaoYz][18:03:49.153][ERRO] file:///home/user/Miao-Yunzai/plugins/chatgpt-plugin/utils/dalle.js:1
import { Configuration, OpenAIApi } from 'openai'
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'openai' does not provide an export named 'Configuration'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async Promise.allSettled (index 2)
    at async file:///home/user/Miao-Yunzai/plugins/chatgpt-plugin/index.js:24:7

**Comment by ikechan8370** [comment]
前几天merge提交了不该提交的内容。
已经回退了package.json 
重新装一下openai依赖吧
