### ISSUE TITLE
与OpenAI通信异常，请稍后重试：Error: SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#96]
与OpenAI通信异常，请稍后重试：Error: SyntaxError: Unexpected non-whitespace character after JSON at position 4

[YzBot][17:02:49.966][ERRO] Error: SyntaxError: Unexpected non-whitespace character after JSON at position
 4
    at ChatGPTPuppeteer.sendMessage (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:496:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async chatgpt (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:231:22)
    at async PluginsLoader.deal (file:///I:/Yunzai-Bot/lib/plugins/loader.js:251:52) {
  statusCode: undefined,
  statusText: undefined
}

**Comment by ikechan8370** [comment]
更新一下

**Comment by TaoXiaoBai** [comment]
> 更新一下

更新以后遇到了以下问题
[YzBot][09:07:53.364][ERRO] Error: net::ERR_PROXY_CONNECTION_FAILED at https://chat.openai.com/chat
    at navigate (I:\Yunzai-Bot\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\common\F
rameManager.js:156:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (I:\Yunzai-Bot\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\li
b\cjs\puppeteer\common\FrameManager.js:131:21)
    at async Frame.goto (I:\Yunzai-Bot\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\
common\FrameManager.js:512:16)
    at async Page.goto (I:\Yunzai-Bot\node_modules\.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\c
ommon\Page.js:1167:16)
    at async ChatGPTPuppeteer.init (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:152:7)
    at async ChatGPTPuppeteer.sendMessage (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:437:27)
    at async chatgpt (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:231:22)
    at async PluginsLoader.deal (file:///I:/Yunzai-Bot/lib/plugins/loader.js:251:52)

**Comment by EternisField** [comment]
> 更新一下

已解决

**Comment by TaoXiaoBai** [comment]
> > 更新一下
> 
> 更新以后遇到了以下问题 [YzBot][09:07:53.364][ERRO] Error: net::ERR_PROXY_CONNECTION_FAILED at [chat.openai.com/chat](https://chat.openai.com/chat) at async Page.goto (I:\Yunzai-Bot\node_modules.pnpm\puppeteer@13.7.0\node_modules\puppeteer\lib\cjs\puppeteer\c ommon\Page.js:1167:16) at async ChatGPTPuppeteer.init (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:152:7) at async ChatGPTPuppeteer.sendMessage (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:437:27) at async chatgpt (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:231:22) at async PluginsLoader.deal (file:///I:/Yunzai-Bot/lib/plugins/loader.js:251:52)

把const PROXY = 'http://127.0.0.1:7890' 设置为空解决了
