### ISSUE TITLE
与OpenAI通信异常，请稍后重试：Error: ChatGPTAPI error 404

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#99]
[YzBot][09:16:46.087][ERRO] Error: ChatGPTAPI error 404
    at ChatGPTPuppeteer.sendMessage (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:496:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async chatgpt (file:///I:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:231:22)
    at async PluginsLoader.deal (file:///I:/Yunzai-Bot/lib/plugins/loader.js:251:52) {
  statusCode: 404,
  statusText: ''
}

**Comment by ikechan8370** [comment]
404可能是对话问题 试着#结束对话 再重新对话

**Comment by TaoXiaoBai** [comment]
> 

感谢，结束对话以后就好了
